"""
Run ScholarQABench evaluation scripts on generated predictions and print
a comparison table against OpenScholar-8B.

Usage:
    python evaluate.py --task scifact
    python evaluate.py --task scifact pubmedqa qasa
    python evaluate.py --task all
    python evaluate.py --task all --compare           # print comparison table
    python evaluate.py --task scholarqa_cs --rubric   # optional GPT-4 rubric eval

Requires:
    - Predictions already generated by benchmark.py in ./predictions/
    - ScholarQABench cloned (set SCHOLARQABENCH_DIR or use default ../ScholarQABench)
    - pip install rouge-score nltk jsonlines
    - python -m nltk.downloader punkt_tab
    - For --rubric: OPENAI_API_KEY must be set
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from src.benchmark_config import BENCHMARK_TASKS, OPENSCHOLAR_8B_SCORES, SCHOLARQABENCH_DIR


# ── Argument parsing ──────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate ScholarQABench predictions")
    parser.add_argument(
        "--task", nargs="+", default=["all"],
        help="Task name(s) to evaluate, or 'all'.",
    )
    parser.add_argument("--suffix", default="finetuned", help="Prediction file suffix (finetuned or base)")
    parser.add_argument("--predictions-dir", default="predictions", help="Directory with prediction files")
    parser.add_argument("--results-dir", default="results", help="Directory for results JSON files")
    parser.add_argument("--compare", action="store_true", help="Print comparison table vs OpenScholar-8B")
    parser.add_argument("--rubric", action="store_true", help="Run GPT-4 rubric eval for scholarqa_cs (needs OPENAI_API_KEY)")
    return parser.parse_args()


# ── Evaluation runners ────────────────────────────────────────────────────────

def _eval_script_path() -> str:
    p = os.path.join(SCHOLARQABENCH_DIR, "scripts", "citation_correctness_eval.py")
    if not os.path.exists(p):
        raise FileNotFoundError(
            f"ScholarQABench eval script not found at {p}\n"
            "Clone https://github.com/AkariAsai/ScholarQABench or set SCHOLARQABENCH_DIR"
        )
    return p


def run_citation_eval(pred_path: str, flags: list[str], results_dir: str, task_name: str, suffix: str) -> dict:
    """Run citation_correctness_eval.py and capture results."""
    script = _eval_script_path()
    scripts_dir = os.path.dirname(script)
    abs_pred_path = os.path.abspath(pred_path)

    cmd = [sys.executable, script, "--f", abs_pred_path] + flags
    print(f"  Running: {' '.join(cmd)}")

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=scripts_dir,  # script imports run_utils from same dir
    )

    if result.returncode != 0:
        print(f"  WARNING: eval script exited with code {result.returncode}")
        print((result.stdout + result.stderr)[-2000:])

    # Save raw stdout+stderr for debugging
    os.makedirs(results_dir, exist_ok=True)
    raw_path = os.path.join(results_dir, f"{task_name}_{suffix}_raw.txt")
    with open(raw_path, "w") as f:
        f.write(result.stdout + result.stderr)

    # Parse scores: prefer the .score_post_fix JSON the script writes
    scores = _read_score_file(abs_pred_path) or _parse_stdout(result.stdout)
    scores = _normalise_keys(scores)

    scores_path = os.path.join(results_dir, f"{task_name}_{suffix}_scores.json")
    with open(scores_path, "w") as f:
        json.dump(scores, f, indent=2)

    print(f"  Scores: {scores}")
    return scores


def _read_score_file(pred_path: str) -> dict | None:
    """Read the .score_post_fix JSON file written by citation_correctness_eval.py."""
    score_path = pred_path + ".score_post_fix"
    if not os.path.exists(score_path):
        return None
    try:
        with open(score_path) as f:
            return json.load(f)
    except Exception:
        return None


def _parse_stdout(stdout: str) -> dict:
    """
    Fallback: find the last line in stdout that looks like a Python dict repr
    and parse it with ast.literal_eval.
    """
    import ast
    for line in reversed(stdout.splitlines()):
        line = line.strip()
        if line.startswith("{") and line.endswith("}"):
            try:
                return ast.literal_eval(line)
            except Exception:
                pass
    return {}


def _normalise_keys(raw: dict) -> dict:
    """
    Map ScholarQABench raw key names to our canonical names and compute F1.
    Raw keys: match, rougeL, rouge1, rouge2, citation_rec, citation_prec, length, str_em, str_hit
    """
    key_map = {
        "match": "accuracy",
        "rougeL": "rouge_l",
        "rouge1": "rouge_1",
        "rouge2": "rouge_2",
        "citation_rec": "citation_recall",
        "citation_prec": "citation_precision",
    }
    out = {}
    for k, v in raw.items():
        canonical = key_map.get(k, k)
        out[canonical] = round(float(v), 2) if isinstance(v, (int, float)) else v

    # Compute citation F1
    rec = out.get("citation_recall")
    prec = out.get("citation_precision")
    if rec is not None and prec is not None and (rec + prec) > 0:
        out["citation_f1"] = round(2 * prec * rec / (prec + rec), 2)

    return out


def run_rubric_eval(pred_path: str, results_dir: str, suffix: str) -> dict:
    """Run ScholarQA-CS GPT-4 rubric eval (optional, needs OPENAI_API_KEY)."""
    if not os.environ.get("OPENAI_API_KEY"):
        print("  SKIP: OPENAI_API_KEY not set. Export it to run rubric eval.")
        return {}

    # Convert predictions to the format expected by rubric_eval.py
    cs_data_dir = os.path.join(SCHOLARQABENCH_DIR, "data", "scholarqa_cs")
    test_config = os.path.join(cs_data_dir, "test_configs_snippets.json")
    converted_path = pred_path.replace(".jsonl", "_rubric_fmt.jsonl")

    convert_script = os.path.join(SCHOLARQABENCH_DIR, "scripts", "convert_answer_scholar_cs.py")
    cmd = [sys.executable, convert_script, "--pred_file", pred_path,
           "--data_file", test_config, "--output_file", converted_path]
    print(f"  Converting: {' '.join(cmd)}")
    subprocess.run(cmd, check=True, cwd=os.path.dirname(convert_script))

    # Run rubric eval
    rubric_script = os.path.join(SCHOLARQABENCH_DIR, "scripts", "rubric_eval.py")
    cmd = [sys.executable, rubric_script,
           "--qa-dir", os.path.dirname(converted_path),
           "--test-config", test_config,
           "--rubrics", "--snippets",
           "--src-names", os.path.basename(converted_path).replace(".jsonl", "")]
    print(f"  Running rubric eval: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=os.path.dirname(rubric_script))

    output = result.stdout + result.stderr
    os.makedirs(results_dir, exist_ok=True)
    raw_path = os.path.join(results_dir, f"scholarqa_cs_{suffix}_rubric_raw.txt")
    with open(raw_path, "w") as f:
        f.write(output)

    scores = _parse_eval_output(output)
    print(f"  Rubric scores: {scores}")
    return scores


# ── Comparison table ──────────────────────────────────────────────────────────

def print_comparison_table(all_scores: dict[str, dict]):
    """Print a markdown comparison table: our model vs OpenScholar-8B."""
    header = f"{'Task':<20} {'Metric':<12} {'Ours':>12} {'OS-8B':>12} {'Delta':>8}"
    print("\n" + "=" * 70)
    print("RESULTS vs OpenScholar-8B")
    print("=" * 70)
    print(header)
    print("-" * 70)

    for task_name, our_scores in sorted(all_scores.items()):
        ref = OPENSCHOLAR_8B_SCORES.get(task_name, {})
        metric = ref.get("metric", "?")

        # Correctness
        corr_key = {"accuracy": "accuracy", "rouge-l": "rouge_l", "rubric": "rubric"}.get(metric)
        our_corr = our_scores.get(corr_key) or our_scores.get("accuracy") or our_scores.get("rouge_l")
        ref_corr = ref.get("correctness")
        if our_corr is not None and ref_corr is not None:
            delta = our_corr - ref_corr
            delta_str = f"{delta:+.1f}"
            print(f"{task_name:<20} {metric:<12} {our_corr:>12.1f} {ref_corr:>12.1f} {delta_str:>8}")
        elif our_corr is not None:
            print(f"{task_name:<20} {metric:<12} {our_corr:>12.1f} {'—':>12} {'—':>8}")

        # Citation F1
        our_cite = our_scores.get("citation_f1")
        ref_cite = ref.get("citation_f1")
        if our_cite is not None:
            if ref_cite is not None:
                delta = our_cite - ref_cite
                delta_str = f"{delta:+.1f}"
                print(f"{'':20} {'cite F1':<12} {our_cite:>12.1f} {ref_cite:>12.1f} {delta_str:>8}")
            else:
                print(f"{'':20} {'cite F1':<12} {our_cite:>12.1f} {'—':>12} {'—':>8}")

    print("=" * 70)
    print("\nTier 1 = fair comparison (gold contexts provided)")
    print("Tier 2 = informational only (no retrieval; expect ~0 citation F1)")
    print("\nOpenScholar-8B uses full RAG pipeline (45M papers). Our model: generation-only.")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    task_names = list(BENCHMARK_TASKS.keys()) if "all" in args.task else args.task
    for name in task_names:
        if name not in BENCHMARK_TASKS:
            print(f"ERROR: Unknown task '{name}'. Choices: {list(BENCHMARK_TASKS.keys())}")
            sys.exit(1)

    all_scores: dict[str, dict] = {}

    for name in task_names:
        task = BENCHMARK_TASKS[name]
        pred_path = os.path.join(args.predictions_dir, f"{task.name}_{args.suffix}.jsonl")

        if not os.path.exists(pred_path):
            print(f"\nSKIP {name}: prediction file not found at {pred_path}")
            print(f"  Run: python benchmark.py --task {name}")
            continue

        print(f"\n{'='*60}")
        print(f"Evaluating: {task.name} (Tier {task.tier}, {args.suffix})")

        scores = run_citation_eval(pred_path, task.eval_flags, args.results_dir, task.name, args.suffix)
        all_scores[name] = scores

        if name == "scholarqa_cs" and args.rubric:
            rubric_scores = run_rubric_eval(pred_path, args.results_dir, args.suffix)
            all_scores[name].update(rubric_scores)

    if args.compare and all_scores:
        print_comparison_table(all_scores)


if __name__ == "__main__":
    main()
